# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: LocalPool

steps:
- checkout: self


- script: mvn clean test
  displayName: 'Run a Maven unit Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    testResultsFormat: 'JUnit'
    failTaskOnMissingResultsFile: true
  displayName: 'Publish Maven Test Results'
  
- script: mvn surefire-report:report
  displayName: 'Generate HTML Test Report'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target/site'
    ArtifactName: 'TestHTMLReport'
    publishLocation: 'Container'
  displayName: 'Publish HTML Test Report Artifact'

   
